apiVersion: apps/v1
kind: Deployment
metadata:
  name: peanut-engine
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: peanut-engine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: peanut-engine
    spec:
      containers:
      - name: peanut-engine
        args: ["--repo-url", "$(REPO_URL)", "--branch", "$(REPO_BRANCH)", "--path", "$(REPO_PATH)", "--resync", "30s"]
        image: bigkevmcd/peanut-engine:latest
        env:
        - name: REPO_URL
          valueFrom:
            configMapKeyRef:
              name: peanut-engine-config
              key: repo_url
        - name: REPO_BRANCH
          valueFrom:
            configMapKeyRef:
              name: peanut-engine-config
              key: repo_branch
        - name: REPO_PATH
          valueFrom:
            configMapKeyRef:
              name: peanut-engine-config
              key: repo_path
      serviceAccountName: peanut-engine
---
apiVersion: v1
kind: Service
metadata:
  name: peanut-engine
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: peanut-engine
  ports:
    - protocol: TCP
      port: 8080
